/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 2.8 */
/* D:\ProgramFiles\Develop\lscc\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n rom_str -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 6 -num_rows 64 -data_width 8 -outdata UNREGISTERED -memfile d:/projects/programs/risc-v_c/xt_risc_v/preload_str.txt -memformat hex  */
/* Fri Jan 31 20:19:19 2025 */


`timescale 1 ns / 1 ps
module rom_str (Address, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [5:0] Address;
    output wire [7:0] Q;


    defparam mem_0_7.initval =  64'h00007E07E003F03F ;
    ROM64X1A mem_0_7 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[7]));

    defparam mem_0_6.initval =  64'h03E2122127309109 ;
    ROM64X1A mem_0_6 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[6]));

    defparam mem_0_5.initval =  64'h000F96FB6E5EDFFB ;
    ROM64X1A mem_0_5 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[5]));

    defparam mem_0_4.initval =  64'h02CFC0F8485C27F2 ;
    ROM64X1A mem_0_4 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[4]));

    defparam mem_0_3.initval =  64'h0512ADAC5D97497E ;
    ROM64X1A mem_0_3 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[3]));

    defparam mem_0_2.initval =  64'h012C1E436F20DE31 ;
    ROM64X1A mem_0_2 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[2]));

    defparam mem_0_1.initval =  64'h07D8954E14A54444 ;
    ROM64X1A mem_0_1 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[1]));

    defparam mem_0_0.initval =  64'h012C02472A40D234 ;
    ROM64X1A mem_0_0 (.AD5(Address[5]), .AD4(Address[4]), .AD3(Address[3]), 
        .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[0]));



    // exemplar begin
    // exemplar end

endmodule
