/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 2.8 */
/* Fri Jan 31 20:19:19 2025 */

/* parameterized module instance */
rom_str __ (.Address( ), .Q( ));
