/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Tue Feb 18 17:26:10 2025 */

/* parameterized module instance */
SystemPLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), 
    .CLKOS3( ), .LOCK( ));
