[target.riscv32i-unknown-none-elf]
runner = "my-emulator"
rustflags = [
    "-C",
    "link-arg=--nmagic",            # 禁用页对齐 降低elf文件大小
    "-C",
    "target-feature=+zicsr,+relax",
]

[build]
target = "riscv32i-unknown-none-elf"
