/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 2.8 */
/* D:\ProgramFiles\Develop\lscc\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n rom_boot -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 8 -num_rows 256 -data_width 32 -outdata REGISTERED -memfile d:/projects/programs/risc-v_c/flatbinarytxt/bootstrap-os.txt -memformat hex  */
/* Thu May 22 16:40:01 2025 */


`timescale 1 ns / 1 ps
module rom_boot (Address, OutClock, OutClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [31:0] Q;

    wire qdataout31_ffin;
    wire qdataout30_ffin;
    wire qdataout29_ffin;
    wire qdataout28_ffin;
    wire qdataout27_ffin;
    wire qdataout26_ffin;
    wire qdataout25_ffin;
    wire qdataout24_ffin;
    wire qdataout23_ffin;
    wire qdataout22_ffin;
    wire qdataout21_ffin;
    wire qdataout20_ffin;
    wire qdataout19_ffin;
    wire qdataout18_ffin;
    wire qdataout17_ffin;
    wire qdataout16_ffin;
    wire qdataout15_ffin;
    wire qdataout14_ffin;
    wire qdataout13_ffin;
    wire qdataout12_ffin;
    wire qdataout11_ffin;
    wire qdataout10_ffin;
    wire qdataout9_ffin;
    wire qdataout8_ffin;
    wire qdataout7_ffin;
    wire qdataout6_ffin;
    wire qdataout5_ffin;
    wire qdataout4_ffin;
    wire qdataout3_ffin;
    wire qdataout2_ffin;
    wire qdataout1_ffin;
    wire qdataout0_ffin;

    FD1P3DX FF_31 (.D(qdataout31_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[31]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(qdataout30_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[30]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(qdataout29_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[29]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(qdataout28_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[28]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(qdataout27_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[27]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(qdataout26_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[26]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(qdataout25_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[25]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(qdataout24_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[24]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(qdataout23_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[23]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(qdataout22_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[22]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(qdataout21_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[21]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(qdataout20_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[20]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(qdataout19_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[19]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(qdataout18_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[18]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(qdataout17_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[17]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(qdataout16_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(qdataout15_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(qdataout14_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(qdataout13_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(qdataout12_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(qdataout11_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(qdataout10_ffin), .SP(OutClockEn), .CK(OutClock), 
        .CD(Reset), .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(qdataout9_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(qdataout8_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(qdataout7_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(qdataout6_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(qdataout5_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(qdataout4_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(qdataout3_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(qdataout2_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(qdataout1_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(qdataout0_ffin), .SP(OutClockEn), .CK(OutClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    defparam mem_0_31.initval = 256'h0000021023E4802422D285FE82B125581C8C2C07C801104040000B0AC0820110 ;
    ROM256X1A mem_0_31 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout31_ffin));

    defparam mem_0_30.initval = 256'h0000021023A4802462D285FE82B125581C8C2C07C801104040000B0AC0A20110 ;
    ROM256X1A mem_0_30 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout30_ffin));

    defparam mem_0_29.initval = 256'h0000021023E48024221287FE8291255A1C8C2D074C81506040000B89D8A20010 ;
    ROM256X1A mem_0_29 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout29_ffin));

    defparam mem_0_28.initval = 256'h0000021023E4802422D285FE809125581C8C3C8748011040C8000B08C0A20010 ;
    ROM256X1A mem_0_28 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout28_ffin));

    defparam mem_0_27.initval = 256'h0000029003A69126261F85FE80E000591C8C3C07D009504051402B0BC0D20110 ;
    ROM256X1A mem_0_27 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout27_ffin));

    defparam mem_0_26.initval = 256'h0000029020548004009203AA4040031B0C800C80680950E0BD006081D82A0014 ;
    ROM256X1A mem_0_26 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout26_ffin));

    defparam mem_0_25.initval = 256'h0000009023A4002420D246FEC0E124D91C8A2C07F819506473002B0AC8801C20 ;
    ROM256X1A mem_0_25 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout25_ffin));

    defparam mem_0_24.initval = 256'h000002840004B0200092015594588A0A591C1402B59762C4159D21205801F350 ;
    ROM256X1A mem_0_24 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout24_ffin));

    defparam mem_0_23.initval = 256'h0000038522228446646744FA408CAD8A0517B40460A9E308699D280950910820 ;
    ROM256X1A mem_0_23 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout23_ffin));

    defparam mem_0_22.initval = 256'h000003843A228002642705EE20CC67088D1194A658F9E2F42D9828C94C90E20C ;
    ROM256X1A mem_0_22 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout22_ffin));

    defparam mem_0_21.initval = 256'h000000A102201444642724AA040007081400C4445169C0902D2028084090D040 ;
    ROM256X1A mem_0_21 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout21_ffin));

    defparam mem_0_20.initval = 256'h000003CC2406D04360E724AA013162683E74840418210E4A11102C0E40948E40 ;
    ROM256X1A mem_0_20 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout20_ffin));

    defparam mem_0_19.initval = 256'h000002002004800040C00000051121600004CD401A0000C00200000000240000 ;
    ROM256X1A mem_0_19 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout19_ffin));

    defparam mem_0_18.initval = 256'h000003FD23A7FD67A4ED05FF829324581FFC60074B2FBF4AE9F07F0CC0D20000 ;
    ROM256X1A mem_0_18 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout18_ffin));

    defparam mem_0_17.initval = 256'h000003FD23A7FD67A4C00000041324580EE40040480F9D40A960640400000000 ;
    ROM256X1A mem_0_17 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout17_ffin));

    defparam mem_0_16.initval = 256'h0000036523A6D56724C00000051325780EE48D4058079DC0AB6064040005FE74 ;
    ROM256X1A mem_0_16 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout16_ffin));

    defparam mem_0_15.initval = 256'h000002DB23A5E74584C001AB0013245800E4004048098140A9606404C0040004 ;
    ROM256X1A mem_0_15 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout15_ffin));

    defparam mem_0_14.initval = 256'h000002AC2005900480C00000001120400174C040080CAE4041B0300000000000 ;
    ROM256X1A mem_0_14 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout14_ffin));

    defparam mem_0_13.initval = 256'h000002882204800400C004FE841120401044804408088840012025080081FE60 ;
    ROM256X1A mem_0_13 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout13_ffin));

    defparam mem_0_12.initval = 256'h00000289A02C88C809C001000011255008644842580E0DC12320260080000083 ;
    ROM256X1A mem_0_12 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout12_ffin));

    defparam mem_0_11.initval = 256'h0000011001A21946240D00AA03AEDC300483AD4000081080820F800080566340 ;
    ROM256X1A mem_0_11 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout11_ffin));

    defparam mem_0_10.initval = 256'h000001FDDE5944B9DB12BFF5B8044E9AF779683FF25FEF17FFF13F7ED7A9A4E0 ;
    ROM256X1A mem_0_10 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout10_ffin));

    defparam mem_0_9.initval = 256'h000001ECC6594C99DB128EDC8A82028A3FF8400CB017FF807DBCB51E01AA8E40 ;
    ROM256X1A mem_0_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout9_ffin));

    defparam mem_0_8.initval = 256'h00000040D9D840B91B12B254B1A892AAC77A4572A257AF1055BE3766062C0117 ;
    ROM256X1A mem_0_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout8_ffin));

    defparam mem_0_7.initval = 256'h000000FC490B4497D116D355D040051B4DF05890C5B0D12441B835A7DA2E0106 ;
    ROM256X1A mem_0_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout7_ffin));

    defparam mem_0_6.initval = 256'h0000021320048A4400C0410040512551088498805C8810E0AA40408188000008 ;
    ROM256X1A mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout6_ffin));

    defparam mem_0_5.initval = 256'h00000313A3EEAFCE4DED47AA447125511C8498C7DDA890E9AA404A8B88F1FFEB ;
    ROM256X1A mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout5_ffin));

    defparam mem_0_4.initval = 256'h000000C8DC5844B97B12BA013BAEDAAEE26B2778A257CD17152FA476772E0197 ;
    ROM256X1A mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout4_ffin));

    defparam mem_0_3.initval = 256'h000002002004800000C0400040512041000410800C8000600000008108000008 ;
    ROM256X1A mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout3_ffin));

    defparam mem_0_2.initval = 256'h00000202A04C828809C0420040712041000410C08C800061000000830820018B ;
    ROM256X1A mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout2_ffin));

    defparam mem_0_1.initval = 256'h000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    ROM256X1A mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout1_ffin));

    defparam mem_0_0.initval = 256'h000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    ROM256X1A mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(qdataout0_ffin));



    // exemplar begin
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
