/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 2.8 */
/* Thu May 22 16:40:01 2025 */

/* parameterized module instance */
rom_boot __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
