/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 6.5 */
/* Tue Jan 07 01:19:47 2025 */

/* parameterized module instance */
SystemInstructionRAM __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
