lib_cfg = true
file_name = 'xtrv32i_wisbone'
version = 'v0.1'
description = '适用于XT_RISC-V_MCU的wisbone总线外设库'
lib_name = 'xtwisbone'
features = ["i2c", "spi", "timer", "flash", "ebf"]
[domain_id]
name = "WISHBONE"
start = 3
end = 4           # 不包含
